version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://alpineac_admin:Alpineace_123@135.181.141.188:3306/alpineac_alpineace
    volumes:
      - .:/app
      - /app/node_modules
